dist: xenial   # required for Python >= 3.7
language: python

matrix:
  include:
    - python: 3.6
      env: TOXENV=py36

    - python: 3.6  # We test the building of the ANTLR grammars only with Python 3.6
      env: TOXENV=antlrgrammars

    - python: 3.6 # We test the lint script only with Python 3.6
      env: TOXENV=pylint

    - python: 3.7
      env: TOXENV=py37

    - python: 3.8-dev
      env: TOXENV=py38

#  pypy doesn't seem to play nice with scipy?
#    - python: pypy3.5
#      env: TOXENV=pypy35

before_install:
  - sudo apt-get install -y --no-install-recommends gringo  # For the ASP-based grounding & rechability tests

install:
  - python -m pip install --upgrade pip setuptools wheel
  - pip install --only-binary=numpy numpy scipy tox
  - tox --version

script:
  - tox
