dist: bionic
language: python

env:
  global:
    # Benchmark locations
    - DOWNWARD_BENCHMARKS="/tmp/downward-benchmarks"
    - FSBENCHMARKS="/tmp/fs-benchmarks"

matrix:
  include:
    # Run the pylint linter with Python 3.6
    - python: 3.7
      env: TOXENV=pylint

    # Test documentation building only with Python 3.6
    - python: 3.7
      env: TOXENV=docs

    # Test the building of the ANTLR grammars only with Python 3.6
    - python: 3.7
      env: TOXENV=antlrgrammars

    # Run the standard pytest tests with different python versions
    - python: 3.6
      env: TOXENV=pycoverage # We check code coverage only with python 3.6

    - python: 3.7
      env: TOXENV=py37

    - python: 3.8
      env: TOXENV=py38

#  pypy doesn't seem to play nice with scipy?
#    - python: pypy3.5
#      env: TOXENV=pypy35 GETBENCHMARKS=true

before_install:
  # Install Gringo only for the ASP-based grounding & rechability tests
  - if [[ $TOXENV == py* ]]; then sudo apt-get install -y --no-install-recommends gringo && gringo --version; fi

  # Install curl for running the codecov script
  - if [[ $TOXENV == pycoverage ]]; then sudo apt-get install -y --no-install-recommends curl; fi


# See:
# - https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/use-conda-with-travis-ci.html
install:
  - if [[ "$TOXENV" == docs ]]; then
      ./scripts/install-conda
   else
    python -m pip install --upgrade tox pip setuptools wheel
    tox --version
    if [[ $TOXENV == py* ]]; then ./scripts/get-benchmarks; fi  # Download benchmarks only if necessary
    if [[ $TOXENV == py* ]]; then pip install Cython --install-option="--no-cython-compile"; fi  # Preinstall Cython if necessary
   fi

script:
  - if [[ "$TOXENV" == docs ]]; then
      ./scripts/build-docs
    else
      tox -vv
    fi